In [26]:
start_number = int(input("Enter Your 1st Number: "))
last_number = int(input("Enter your 2nd number: "))
for i in range(start_number,last_number+1):
    for j in range(1,11):
        print(f"{start_number} x {j} = {start_number*j}")
    print("\t")
    start_number += 1

Enter Your 1st Number: 2
Enter your 2nd number: 8
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20

3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30

4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40

5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50

6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
6 x 10 = 60

7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70

8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
8 x 10 = 80

In [28]:
first_number = int(input("Enter 1st number: "))
last_number = int(input("Enter 2nd number: "))
for j in range(1,11):
    for i in range(first_number,last_number+1):
        print(f"{i} x {j} = {i*j}",end="\t")
    print("\n")

Enter 1st number: 2
Enter 2nd number: 8
2 x 1 = 2	3 x 1 = 3	4 x 1 = 4	5 x 1 = 5	6 x 1 = 6	7 x 1 = 7	8 x 1 = 8

2 x 2 = 4	3 x 2 = 6	4 x 2 = 8	5 x 2 = 10	6 x 2 = 12	7 x 2 = 14	8 x 2 = 16

2 x 3 = 6	3 x 3 = 9	4 x 3 = 12	5 x 3 = 15	6 x 3 = 18	7 x 3 = 21	8 x 3 = 24

2 x 4 = 8	3 x 4 = 12	4 x 4 = 16	5 x 4 = 20	6 x 4 = 24	7 x 4 = 28	8 x 4 = 32

2 x 5 = 10	3 x 5 = 15	4 x 5 = 20	5 x 5 = 25	6 x 5 = 30	7 x 5 = 35	8 x 5 = 40

2 x 6 = 12	3 x 6 = 18	4 x 6 = 24	5 x 6 = 30	6 x 6 = 36	7 x 6 = 42	8 x 6 = 48

2 x 7 = 14	3 x 7 = 21	4 x 7 = 28	5 x 7 = 35	6 x 7 = 42	7 x 7 = 49	8 x 7 = 56

2 x 8 = 16	3 x 8 = 24	4 x 8 = 32	5 x 8 = 40	6 x 8 = 48	7 x 8 = 56	8 x 8 = 64

2 x 9 = 18	3 x 9 = 27	4 x 9 = 36	5 x 9 = 45	6 x 9 = 54	7 x 9 = 63	8 x 9 = 72

2 x 10 = 20	3 x 10 = 30	4 x 10 = 40	5 x 10 = 50	6 x 10 = 60	7 x 10 = 70	8 x 10 = 80

In [1]:
import pprint
record = []
end_of_list = int(input("How many users you want to add: "))
for i in range(0,end_of_list): 
    person = {
        "Name":input("Enter Your Name: "),
        "Age":int(input("Enter your Age: ")),
        "Work":input("Enter your work: "),
        "Skill": [input("Enter your Skills Separated by Commas: ").split(",")],
        "Degree":{
            "Title":input("Enter your degree title: "),
            "Major":input("Enter your major Subject: "),
            "Completion_date":input("Enter your Completion Date: ")
        },
        "Salary":input("Enter your Salary: ")
 
    }
    record.append(person)
print("--------------------------------------------------------------------------------------------------------")
pprint.pprint(record)

How many users you want to add: 2
Enter Your Name: Naveed Mughal
Enter your Age: 21
Enter your work: AI
Enter your Skills Separated by Commas: Python,C#,C,C++
Enter your degree title: BS
Enter your major Subject: Computer Science
Enter your Completion Date: 2020
Enter your Salary: 70000
Enter Your Name: Mohsin
Enter your Age: 23
Enter your work: Web
Enter your Skills Separated by Commas: python,IOT,
Enter your degree title: BS
Enter your major Subject: Computer Science
Enter your Completion Date: 2020
Enter your Salary: 50000
--------------------------------------------------------------------------------------------------------
[{'Age': 21,
  'Degree': {'Completion_date': '2020',
             'Major': 'Computer Science',
             'Title': 'BS'},
  'Name': 'Naveed Mughal',
  'Salary': '70000',
  'Skill': [['Python', 'C#', 'C', 'C++']],
  'Work': 'AI'},
 {'Age': 23,
  'Degree': {'Completion_date': '2020',
             'Major': 'Computer Science',
             'Title': 'BS'},
  'Name': 'Mohsin',
  'Salary': '50000',
  'Skill': [['python', 'IOT', '']],
  'Work': 'Web'}]